name: Build and run tests

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd typescript
          yarn install --immutable
          yarn build
          yarn lint

          mkdir deployable
          cp index.html deployable
          mv dist deployable
          cp -r static/* deployable

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployable
